spring:
  application:
    name: programmers spring assignments
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

jwt:
  token:
    client-secret: 3c69e85afb6e4c9f8c7f0960a15a024e123124asdf32r4asdfsdaf12sajfas2187364786asdfas
    expiration: 6000000
